[package]
name = "socal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
httparse = "1.8.0"
hyper = "1.3.1"
lazy_static = "1.4.0"
oauth2 = "4.4.2"
regex = "1.10.4"
url = "2.5.0"
